# Generated by Django 5.0.3 on 2024-04-12 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="название")),
                ("photo", models.ImageField(upload_to="")),
                (
                    "add_price",
                    models.PositiveSmallIntegerField(
                        verbose_name="цена добавления в продукт"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calories", models.PositiveSmallIntegerField(verbose_name="калории")),
                ("weight", models.PositiveSmallIntegerField(verbose_name="вес")),
                ("editable", models.BooleanField(verbose_name="редактируемо")),
                (
                    "extra_ingredients",
                    models.ManyToManyField(
                        related_name="extra", to="products.ingredient"
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        related_name="ingredients", to="products.ingredient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_ingredient",
                    models.ManyToManyField(
                        related_name="added", to="products.ingredient"
                    ),
                ),
                (
                    "base_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.baseproduct",
                    ),
                ),
                (
                    "removed_ingredient",
                    models.ManyToManyField(
                        related_name="removed", to="products.ingredient"
                    ),
                ),
            ],
        ),
    ]
