# Generated by Django 5.0.3 on 2024-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="photo",
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="base_products/"),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="ingredients/"),
        ),
    ]
