# Generated by Django 5.0.3 on 2024-04-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_ingredient_photo_baseproduct_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="название"),
        ),
    ]
