# Generated by Django 5.0.3 on 2024-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_baseproduct_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Пицца", "Пицца"),
                    ("Напиток", "Напиток"),
                    ("Закуска", "Закуска"),
                    ("Соус", "Соус"),
                ],
                max_length=50,
                null=True,
                verbose_name="тип продукта",
            ),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="extra_ingredients",
            field=models.ManyToManyField(
                related_name="extra",
                to="products.ingredient",
                verbose_name="доп ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="base_products/", verbose_name="фото"
            ),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients",
                to="products.ingredient",
                verbose_name="ингредиенты",
            ),
        ),
    ]
