# Generated by Django 5.0.3 on 2024-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_baseproduct_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Маленький", "Маленький"),
                    ("Средний", "Средний"),
                    ("Большой", "Большой"),
                ],
                max_length=20,
                null=True,
                verbose_name="размер",
            ),
        ),
    ]
