# Generated by Django 5.0.3 on 2024-04-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_baseproduct_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="тип")),
                ("sizable", models.BooleanField(verbose_name="изменяемый размер")),
                ("sizes", models.JSONField(verbose_name="размеры")),
                ("extra_fields", models.JSONField(verbose_name="доп. поля")),
            ],
        ),
        migrations.RemoveField(
            model_name="baseproduct",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="baseproduct",
            name="size",
        ),
        migrations.RemoveField(
            model_name="baseproduct",
            name="weight",
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="цена"),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="product_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.producttype",
                verbose_name="тип продукта",
            ),
        ),
    ]
