# Generated by Django 5.0.3 on 2024-04-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_producttype_remove_baseproduct_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="extra_fields",
            field=models.JSONField(blank=True, null=True, verbose_name="доп. поля"),
        ),
    ]
