# Generated by Django 5.0.3 on 2024-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_alter_producttype_extra_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseproduct",
            name="price",
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="prices",
            field=models.JSONField(null=True, verbose_name="цены"),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="sizable",
            field=models.BooleanField(default=False, verbose_name="изменяемый размер"),
        ),
    ]
