# Generated by Django 5.0.3 on 2024-05-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_remove_baseproduct_price_baseproduct_prices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="label",
            field=models.CharField(
                max_length=30, null=True, verbose_name="тип во мн. числе"
            ),
        ),
        migrations.AddField(
            model_name="producttype",
            name="label_id",
            field=models.CharField(
                max_length=30, null=True, verbose_name="тип на анг. языке"
            ),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="extra_ingredients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="extra",
                to="products.ingredient",
                verbose_name="доп ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="ingredients",
                to="products.ingredient",
                verbose_name="ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="orderedproduct",
            name="added_ingredient",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="added", to="products.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="orderedproduct",
            name="removed_ingredient",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="removed", to="products.ingredient"
            ),
        ),
    ]
