# Generated by Django 5.0.3 on 2024-05-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_baseproduct_extra_ingredients_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="number",
            field=models.IntegerField(default=1, verbose_name="количество"),
        ),
    ]
