# Generated by Django 5.0.3 on 2024-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_orderedproduct_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="price",
            field=models.IntegerField(default=0, verbose_name="цена"),
        ),
    ]
