# Generated by Django 5.0.3 on 2024-05-10 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_orderedproduct_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderedproduct",
            old_name="number",
            new_name="quantity",
        ),
    ]
