# Generated by Django 5.0.3 on 2024-05-23 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_orderedproduct_ingredients_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedproduct",
            name="base_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordered_products",
                to="products.baseproduct",
            ),
        ),
    ]
