# Generated by Django 5.0.3 on 2024-05-26 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_alter_orderedproduct_base_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseproduct",
            options={"verbose_name": "продукт", "verbose_name_plural": "продукты"},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"verbose_name": "ингредиент", "verbose_name_plural": "ингредиент"},
        ),
        migrations.AlterModelOptions(
            name="orderedproduct",
            options={
                "verbose_name": "заказанный продукт",
                "verbose_name_plural": "заказанные продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "verbose_name": "тип продукта",
                "verbose_name_plural": "Типы продуктов",
            },
        ),
    ]
