# Generated by Django 5.0.3 on 2024-05-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0018_alter_baseproduct_options_alter_ingredient_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttype",
            name="sizes",
            field=models.JSONField(blank=True, null=True, verbose_name="размеры"),
        ),
    ]
