# Generated by Django 5.0.3 on 2024-05-03 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_delete_paymentmethod"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="last_numbers",
            field=models.CharField(max_length=5),
        ),
        migrations.RemoveField(
            model_name="card",
            name="user",
        ),
        migrations.AddField(
            model_name="card",
            name="user",
            field=models.ManyToManyField(
                related_name="cards", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
