# Generated by Django 5.0.3 on 2024-05-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0005_alter_card_last_numbers_remove_card_user_card_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="user",
            new_name="card_users",
        ),
        migrations.AlterField(
            model_name="card",
            name="last_numbers",
            field=models.CharField(max_length=20),
        ),
    ]
