# Generated by Django 5.0.3 on 2024-05-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_rename_user_card_card_users_alter_card_last_numbers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"verbose_name": "карта", "verbose_name_plural": "карты"},
        ),
        migrations.AlterField(
            model_name="card",
            name="last_numbers",
            field=models.CharField(max_length=20, verbose_name="номер карты"),
        ),
    ]
