# Generated by Django 5.0.3 on 2024-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_token",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="имя в телеграм"
            ),
        ),
    ]
