# Generated by Django 5.0.3 on 2024-05-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="entrance",
            field=models.CharField(max_length=5, null=True, verbose_name="подъезд"),
        ),
        migrations.AddField(
            model_name="address",
            name="flat",
            field=models.CharField(max_length=5, null=True, verbose_name="квартира"),
        ),
        migrations.AddField(
            model_name="address",
            name="floor",
            field=models.CharField(max_length=5, null=True, verbose_name="этаж"),
        ),
    ]
