# Generated by Django 5.0.3 on 2024-05-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_address_entrance_address_flat_address_floor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "адрес", "verbose_name_plural": "адреса"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="entrance",
            field=models.IntegerField(null=True, verbose_name="подъезд"),
        ),
        migrations.AlterField(
            model_name="address",
            name="flat",
            field=models.IntegerField(null=True, verbose_name="квартира"),
        ),
        migrations.AlterField(
            model_name="address",
            name="floor",
            field=models.IntegerField(null=True, verbose_name="этаж"),
        ),
    ]
