# Generated by Django 5.0.3 on 2024-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products_sum",
            field=models.IntegerField(default=0, verbose_name="сумма заказа"),
        ),
    ]
