# Generated by Django 5.0.3 on 2024-05-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_cart_products_sum"),
        ("products", "0013_orderedproduct_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="carts", to="products.orderedproduct"
            ),
        ),
    ]
