# Generated by Django 5.0.3 on 2024-05-26 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_cart_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "корзина", "verbose_name_plural": "корзины"},
        ),
    ]
