# Generated by Django 5.0.3 on 2024-05-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
        ("payment", "0003_remove_paymentmethod_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.card",
                verbose_name="способ оплаты",
            ),
        ),
    ]
