# Generated by Django 5.0.3 on 2024-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_alter_order_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="дата заказа"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Готовится", "Готовится"),
                    ("Приготовлен", "Приготовлен"),
                    ("Передан курьеру", "Передан курьеру"),
                    ("Доставлен", "Доставлен"),
                ],
                default="Готовится",
                max_length=30,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="to_time",
            field=models.TimeField(blank=True, verbose_name="доставка ко времени"),
        ),
    ]
