# Generated by Django 5.0.3 on 2024-05-26 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_order_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "заказ", "verbose_name_plural": "заказы"},
        ),
        migrations.AlterModelOptions(
            name="orderstatuslog",
            options={
                "verbose_name": "лог заказа",
                "verbose_name_plural": "логи заказов",
            },
        ),
    ]
