# Generated by Django 5.0.3 on 2024-05-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_alter_order_options_alter_orderstatuslog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="to_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="доставка ко времени"
            ),
        ),
    ]
